### ISSUE TITLE
155 Min Stack.py gives a TLE error in push()

### ISSUE THREAD

**Issue by anantzoid** [algorhythms/LeetCode#5]
I tried doing self.stack.append(x) and self.stack = [x]+self.stack, but I get the error in both cases.

**Comment by idf** [comment]
Hi Gupta. I re-submitted my code to the OJ and it accepted my code.
<img width="689" alt="screen shot 2015-07-25 at 21 50 31" src="https://cloud.githubusercontent.com/assets/2493622/8889686/39ef992a-3317-11e5-8050-3751e30fc7b9.png">

What is your code and error message?

And do note the `self.stack = [x]+self.stack` takes O(N) rather than O(1).
